### PR TITLE
Use strings to pass test args with semicolons #464

### PR DESCRIPTION
**Pull request by mzuzek**
Here's some experimental code based on https://github.com/TriBITSPub/TriBITS/pull/464 that aims to find out exact limitations on how semicolons in test command line and environment are handled by CMake. By passing strings around - instead of lists - one can enable test command line arguments to be configured like:
```erlang
tribits_add_advanced_test(
  CTestScripts_taat_cmnd_1_args_with_semicolon_and_spaces
  TEST_0 EXEC GenericDriver ARGS "arg\;with\;semicolons and\;several spaces" 0
    PASS_REGULAR_EXPRESSION "arg[;]with[;]semicolons and[;]several spaces"
  OVERALL_NUM_MPI_PROCS 1
  )
```
and environment variables like:
```erlang
tribits_add_test("${CMAKE_COMMAND}" NOEXEPREFIX NOEXESUFFIX
  NAME CTestScripts_tat_env_vars_with_semicolon_and_spaces
  POSTFIX_AND_ARGS_0 ""
    -DENV_VAR_0=MY_ENV_VAR_0
    -DENV_VAR_1=MY_ENV_VAR_1
    -P "${CMAKE_CURRENT_LIST_DIR}/echoEnvVars.cmake"
  PASS_REGULAR_EXPRESSION
      "MY_ENV_VAR_0 = 'val 0a[;]val 0b[;]val 0c'\nMY_ENV_VAR_1 = 'val 1a[;]val 1b[;]val 1c'"
  ENVIRONMENT
    "MY_ENV_VAR_0=val 0a;val 0b;val 0c"
    "MY_ENV_VAR_1=val 1a;val 1b;val 1c"
  NUM_MPI_PROCS 1
  )
```

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
This is pretty pretty tricky code where lists of arguments need to be quoted to get this to work.  The `LIST_SEPARATOR` approach removes all of the trickiness of needing to figure out where you have to quote an entire list and where you don't.  If playing games like this was a workable solution, Kitware would have done it.

**Comment by bartlettroscoe** [comment]
Thanks for documenting this experiment but we need to stick with TriBITSPub/TriBITS#464 as per https://github.com/TriBITSPub/TriBITS/pull/464#issuecomment-1074264366.  Closing as "wontfix"

**Comment by bartlettroscoe** [comment]
Thanks for documenting this experiment but we need to stick with TriBITSPub/TriBITS#464 as per https://github.com/TriBITSPub/TriBITS/pull/464#issuecomment-1074264366.  Closing as "wontfix"

**Comment by mzuzek** [comment]
@bartlettroscoe Understood, thank you for checking.

**Pull request closed without merging**
